"""Fast structured PII detection implemented in Rust."""

from .datafog_core import (
    DataFogConfigurationError as DataFogConfigurationError,
    DataFogFindingError as DataFogFindingError,
    DataFogInternalError as DataFogInternalError,
    DataFogKeyProviderError as DataFogKeyProviderError,
    FieldMapping as FieldMapping,
    Finding as Finding,
    PrivacyManager as PrivacyManager,
    Restoration as Restoration,
    RestoreResult as RestoreResult,
    StructuredFinding as StructuredFinding,
    StructuredRestoration as StructuredRestoration,
    StructuredRestoreResult as StructuredRestoreResult,
    StructuredScanResult as StructuredScanResult,
    StructuredTransformation as StructuredTransformation,
    StructuredTransformResult as StructuredTransformResult,
    TextRange as TextRange,
    Transformation as Transformation,
    TransformResult as TransformResult,
    discover_fields as discover_fields,
    scan as scan,
    scan_and_transform as scan_and_transform,
    scan_and_transform_structured as scan_and_transform_structured,
    scan_structured as scan_structured,
    transform as transform,
    transform_structured as transform_structured,
)

__all__ = [
    "DataFogConfigurationError",
    "DataFogFindingError",
    "DataFogInternalError",
    "DataFogKeyProviderError",
    "TextRange",
    "Finding",
    "Transformation",
    "TransformResult",
    "Restoration",
    "RestoreResult",
    "FieldMapping",
    "StructuredFinding",
    "StructuredScanResult",
    "StructuredTransformation",
    "StructuredTransformResult",
    "StructuredRestoration",
    "StructuredRestoreResult",
    "PrivacyManager",
    "scan",
    "transform",
    "scan_and_transform",
    "discover_fields",
    "scan_structured",
    "transform_structured",
    "scan_and_transform_structured",
]
